// Demo mode data — realistic sample data for local preview
// None of this touches Supabase.

export const MOCK_USER = {
  id: 'demo-user-1',
  email: 'aditya@retreat.app',
}

export const MOCK_PROFILE = {
  id: 'demo-user-1',
  full_name: 'Aditya',
  role: 'admin',
}

const now = new Date()
const daysAgo = (n) => new Date(now - n * 86400000).toISOString().split('T')[0]
const daysFromNow = (n) => new Date(now.getTime() + n * 86400000).toISOString().split('T')[0]

export const MOCK_COMPANIES = [
  {
    id: 'co-1',
    company_name: 'Goldman Sachs',
    industry: 'Finance / Banking',
    website: 'https://goldmansachs.com',
    internal_owner: 'demo-user-1',
    target_sponsorship_level: 'premier',
    confirmed_sponsorship_level: 'premier',
    outreach_status: 'confirmed',
    first_contact_date: daysAgo(45),
    last_contact_date: daysAgo(10),
    next_follow_up_date: null,
    documents_sent: ['Sponsorship Packet', 'Budget Breakdown'],
    tags: ['high-priority', 'alumni-connection'],
    notes_preview: 'VP of Campus Recruiting is an alum. Very warm intro via Prof. Chen.',
    created_at: new Date(now - 50 * 86400000).toISOString(),
    updated_at: new Date(now - 10 * 86400000).toISOString(),
    contacts: [{ id: 'ct-1', company_id: 'co-1', name: 'Sarah Kim', title: 'Campus Recruiting Lead', email: 'skim@gs.com', phone: '(212) 555-0101', is_primary: true }],
    owner: { id: 'demo-user-1', full_name: 'Aditya' },
  },
  {
    id: 'co-2',
    company_name: 'McKinsey & Company',
    industry: 'Consulting',
    website: 'https://mckinsey.com',
    internal_owner: 'demo-user-2',
    target_sponsorship_level: 'platinum',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'interested',
    first_contact_date: daysAgo(30),
    last_contact_date: daysAgo(7),
    next_follow_up_date: daysFromNow(3),
    documents_sent: ['Sponsorship Packet'],
    tags: ['consulting', 'needs-deck-update'],
    notes_preview: 'Spoke with James — interested in Platinum but needs updated packet. Decision by end of month.',
    created_at: new Date(now - 35 * 86400000).toISOString(),
    updated_at: new Date(now - 7 * 86400000).toISOString(),
    contacts: [{ id: 'ct-2', company_id: 'co-2', name: 'James Park', title: 'Recruiting Manager', email: 'jpark@mckinsey.com', phone: '(617) 555-0202', is_primary: true }],
    owner: { id: 'demo-user-2', full_name: 'Shepard' },
  },
  {
    id: 'co-3',
    company_name: 'Google',
    industry: 'Technology',
    website: 'https://google.com',
    internal_owner: 'demo-user-1',
    target_sponsorship_level: 'silver',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'follow_up_sent',
    first_contact_date: daysAgo(20),
    last_contact_date: daysAgo(8),
    next_follow_up_date: daysFromNow(1),
    documents_sent: ['Sponsorship Packet', 'Past Retreat Summary'],
    tags: ['tech', 'large-company'],
    notes_preview: 'Initial email sent, no response yet. Sent follow-up last Thursday.',
    created_at: new Date(now - 22 * 86400000).toISOString(),
    updated_at: new Date(now - 8 * 86400000).toISOString(),
    contacts: [{ id: 'ct-3', company_id: 'co-3', name: 'Priya Nair', title: 'University Programs', email: 'pnair@google.com', phone: null, is_primary: true }],
    owner: { id: 'demo-user-1', full_name: 'Aditya' },
  },
  {
    id: 'co-4',
    company_name: 'Blackstone',
    industry: 'Finance / Banking',
    website: 'https://blackstone.com',
    internal_owner: 'demo-user-2',
    target_sponsorship_level: 'silver',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'contacted',
    first_contact_date: daysAgo(14),
    last_contact_date: daysAgo(14),
    next_follow_up_date: daysFromNow(0), // today
    documents_sent: ['Sponsorship Packet'],
    tags: ['finance', 'new-relationship'],
    notes_preview: 'Cold outreach via LinkedIn. Ryan replied and asked for more info.',
    created_at: new Date(now - 15 * 86400000).toISOString(),
    updated_at: new Date(now - 14 * 86400000).toISOString(),
    contacts: [{ id: 'ct-4', company_id: 'co-4', name: 'Ryan Torres', title: 'HR Business Partner', email: 'rtorres@blackstone.com', phone: '(212) 555-0303', is_primary: true }],
    owner: { id: 'demo-user-2', full_name: 'Shepard' },
  },
  {
    id: 'co-5',
    company_name: 'Deloitte',
    industry: 'Consulting',
    website: 'https://deloitte.com',
    internal_owner: 'demo-user-1',
    target_sponsorship_level: 'bronze',
    confirmed_sponsorship_level: 'bronze',
    outreach_status: 'confirmed',
    first_contact_date: daysAgo(60),
    last_contact_date: daysAgo(20),
    next_follow_up_date: null,
    documents_sent: ['Sponsorship Packet', 'Thank You Letter'],
    tags: ['confirmed', 'returning-sponsor'],
    notes_preview: 'Returning sponsor from last year. Easy conversation, quick sign-off.',
    created_at: new Date(now - 62 * 86400000).toISOString(),
    updated_at: new Date(now - 20 * 86400000).toISOString(),
    contacts: [{ id: 'ct-5', company_id: 'co-5', name: 'Michelle Lee', title: 'Campus Relations', email: 'mlee@deloitte.com', phone: '(312) 555-0404', is_primary: true }],
    owner: { id: 'demo-user-1', full_name: 'Aditya' },
  },
  {
    id: 'co-6',
    company_name: 'Citadel',
    industry: 'Finance / Banking',
    website: 'https://citadel.com',
    internal_owner: 'demo-user-2',
    target_sponsorship_level: 'gold',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'declined',
    first_contact_date: daysAgo(40),
    last_contact_date: daysAgo(25),
    next_follow_up_date: null,
    documents_sent: ['Sponsorship Packet'],
    tags: ['declined', 'try-next-year'],
    notes_preview: 'Budget fully allocated for this cycle. Suggested we reach out in September for next year.',
    created_at: new Date(now - 42 * 86400000).toISOString(),
    updated_at: new Date(now - 25 * 86400000).toISOString(),
    contacts: [{ id: 'ct-6', company_id: 'co-6', name: 'Alex Chen', title: 'Talent Acquisition', email: 'achen@citadel.com', phone: null, is_primary: true }],
    owner: { id: 'demo-user-2', full_name: 'Shepard' },
  },
  {
    id: 'co-7',
    company_name: 'Bain & Company',
    industry: 'Consulting',
    website: 'https://bain.com',
    internal_owner: 'demo-user-1',
    target_sponsorship_level: 'silver',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'ready_to_contact',
    first_contact_date: null,
    last_contact_date: null,
    next_follow_up_date: daysFromNow(2),
    documents_sent: [],
    tags: ['consulting', 'warm-intro-pending'],
    notes_preview: 'Prof. Williams said she can make an intro. Waiting on her to send the email.',
    created_at: new Date(now - 5 * 86400000).toISOString(),
    updated_at: new Date(now - 2 * 86400000).toISOString(),
    contacts: [],
    owner: { id: 'demo-user-1', full_name: 'Aditya' },
  },
  {
    id: 'co-8',
    company_name: 'Amazon',
    industry: 'Technology',
    website: 'https://amazon.com',
    internal_owner: 'demo-user-1',
    target_sponsorship_level: 'silver',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'not_started',
    first_contact_date: null,
    last_contact_date: null,
    next_follow_up_date: null,
    documents_sent: [],
    tags: ['tech'],
    notes_preview: '',
    created_at: new Date(now - 3 * 86400000).toISOString(),
    updated_at: new Date(now - 3 * 86400000).toISOString(),
    contacts: [],
    owner: { id: 'demo-user-1', full_name: 'Aditya' },
  },
  {
    id: 'co-9',
    company_name: 'JPMorgan Chase',
    industry: 'Finance / Banking',
    website: 'https://jpmorganchase.com',
    internal_owner: 'demo-user-2',
    target_sponsorship_level: 'gold',
    confirmed_sponsorship_level: 'none',
    outreach_status: 'on_hold',
    first_contact_date: daysAgo(25),
    last_contact_date: daysAgo(18),
    next_follow_up_date: daysAgo(3), // overdue
    documents_sent: ['Sponsorship Packet'],
    tags: ['on-hold', 'internal-review'],
    notes_preview: 'On hold — contact said sponsorship decisions go through a committee. Checking back in two weeks.',
    created_at: new Date(now - 28 * 86400000).toISOString(),
    updated_at: new Date(now - 18 * 86400000).toISOString(),
    contacts: [{ id: 'ct-9', company_id: 'co-9', name: 'Dana Walsh', title: 'Early Careers', email: 'dwalsh@jpmorgan.com', phone: '(212) 555-0505', is_primary: true }],
    owner: { id: 'demo-user-2', full_name: 'Shepard' },
  },
]

export const MOCK_ACTIVITIES = [
  { id: 'act-1', company_id: 'co-1', type: 'confirmed', description: 'Sponsorship confirmed at Premier Corporate Sponsor level', created_by: 'demo-user-1', created_at: new Date(now - 10 * 86400000).toISOString(), actor: { id: 'demo-user-1', full_name: 'Aditya' }, company: { id: 'co-1', company_name: 'Goldman Sachs' } },
  { id: 'act-2', company_id: 'co-2', type: 'follow_up_logged', description: 'Follow-up call — interested in Platinum, needs updated packet', created_by: 'demo-user-2', created_at: new Date(now - 7 * 86400000).toISOString(), actor: { id: 'demo-user-2', full_name: 'Shepard' }, company: { id: 'co-2', company_name: 'McKinsey & Company' } },
  { id: 'act-3', company_id: 'co-3', type: 'outreach_sent', description: 'Follow-up email sent after no response', created_by: 'demo-user-1', created_at: new Date(now - 8 * 86400000).toISOString(), actor: { id: 'demo-user-1', full_name: 'Aditya' }, company: { id: 'co-3', company_name: 'Google' } },
  { id: 'act-4', company_id: 'co-4', type: 'status_changed', description: 'Status changed from "ready_to_contact" to "contacted"', created_by: 'demo-user-2', created_at: new Date(now - 14 * 86400000).toISOString(), actor: { id: 'demo-user-2', full_name: 'Shepard' }, company: { id: 'co-4', company_name: 'Blackstone' } },
  { id: 'act-5', company_id: 'co-5', type: 'confirmed', description: 'Sponsorship confirmed at Bronze Corporate Sponsor level', created_by: 'demo-user-1', created_at: new Date(now - 20 * 86400000).toISOString(), actor: { id: 'demo-user-1', full_name: 'Aditya' }, company: { id: 'co-5', company_name: 'Deloitte' } },
  { id: 'act-6', company_id: 'co-7', type: 'created', description: 'Bain & Company was added to the CRM', created_by: 'demo-user-1', created_at: new Date(now - 5 * 86400000).toISOString(), actor: { id: 'demo-user-1', full_name: 'Aditya' }, company: { id: 'co-7', company_name: 'Bain & Company' } },
  { id: 'act-7', company_id: 'co-9', type: 'status_changed', description: 'Status changed to "on_hold" — pending committee review', created_by: 'demo-user-2', created_at: new Date(now - 18 * 86400000).toISOString(), actor: { id: 'demo-user-2', full_name: 'Shepard' }, company: { id: 'co-9', company_name: 'JPMorgan Chase' } },
  { id: 'act-8', company_id: 'co-2', type: 'note_added', description: 'Note added', created_by: 'demo-user-2', created_at: new Date(now - 9 * 86400000).toISOString(), actor: { id: 'demo-user-2', full_name: 'Shepard' }, company: { id: 'co-2', company_name: 'McKinsey & Company' } },
]

export const MOCK_NOTES = {
  'co-1': [
    { id: 'n-1', company_id: 'co-1', author_id: 'demo-user-1', content: 'Sarah was super responsive — she remembered us from last year\'s retreat. Said their campus team loves this kind of event. Confirmed Gold.', created_at: new Date(now - 10 * 86400000).toISOString(), author: { id: 'demo-user-1', full_name: 'Aditya' } },
    { id: 'n-2', company_id: 'co-1', author_id: 'demo-user-1', content: 'Sent sponsorship packet + budget breakdown. They want logo placement on all printed materials and a 10-min speaking slot during the Friday dinner.', created_at: new Date(now - 30 * 86400000).toISOString(), author: { id: 'demo-user-1', full_name: 'Aditya' } },
  ],
  'co-2': [
    { id: 'n-3', company_id: 'co-2', author_id: 'demo-user-2', content: 'James said their recruiting budget is tight but he\'s pushing for Platinum internally. Decision by end of month. Updated packet needed — they want to see the retreat agenda and past attendance numbers.', created_at: new Date(now - 7 * 86400000).toISOString(), author: { id: 'demo-user-2', full_name: 'Shepard' } },
  ],
  'co-9': [
    { id: 'n-4', company_id: 'co-9', author_id: 'demo-user-2', content: 'Dana said it goes through a "community investment committee" that meets monthly. We missed the last meeting window. Follow up after the 15th.', created_at: new Date(now - 18 * 86400000).toISOString(), author: { id: 'demo-user-2', full_name: 'Shepard' } },
  ],
}

export const MOCK_PROFILES = [
  { id: 'demo-user-1', full_name: 'Aditya', role: 'admin' },
  { id: 'demo-user-2', full_name: 'Shepard', role: 'co_admin' },
]
